### ISSUE TITLE
[NativeMediaPlayer] Editor crashes when press start

### ISSUE THREAD

**Issue by amaiichigopurin** [Glitch9Inc/Glitch9-Support#2] opened 2024-06-29 01:59 UTC
private static readonly Prefs<UriType> _currentUriType = new(PrefsKeys.URI_TYPE);

Still crashes both real hardware and unity. I would take a look at that before updating the asset store package.

**Comment by Glitch9Inc** [comment] 2024-06-29 02:11
Added fix on version 4.2.4

**Comment by Glitch9Inc** [comment] 2024-06-29 02:12
Added another fix on version 4.2.5

**Comment by Glitch9Inc** [comment] 2024-06-29 02:13
Some users still experiencing the crash, I might be related to this issue. Not closing until it's clear this is not the cause of the crash.

**Comment by Manurocker95** [comment] 2024-06-29 07:03
> private static readonly Prefs _currentUriType = new(PrefsKeys.URI_TYPE);
> 
> Still crashes both real hardware and unity. I would take a look at that before updating the asset store package.

From latest store update of the asset, a new parameter is set but the app is still crashing. The error is related to some function in the DLL without the proper name.

**Comment by Glitch9Inc** [comment] 2024-06-29 09:03
Added more robust error handlings to Prefs.cs
https://github.com/Glitch9Inc/Unity.CoreLib/blob/main/System/PlayerPrefs/Prefs.cs

**Comment by Manurocker95** [comment] 2024-06-29 10:26
PlayerPrefs should probably move to saved binary in persistentDataPath

**Comment by Glitch9Inc** [comment] 2024-06-29 10:34
> PlayerPrefs should probably move to saved binary in persistentDataPath

In the past, the media data (playlist) was also saved in persistentDataPath instead of PlayerPrefs. However, since SDK 30 or something, saving to local disk on Android requires an extra permission for anything other than media files. Many customers found it challenging to explain to their users why this permission was needed, as it can be difficult for those not familiar with programming to understand.

To address these concerns and make things simpler for the users, I moved the data storage to PlayerPrefs.

**Closed as completed** 2024-07-01 13:16 UTC
Labels: bug
