### ISSUE TITLE
[NativeMediaPlayer] [BUG] Seek bar not working in background controls

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#11] opened 2024-06-29 07:10 UTC
Stop, 10 secs forward, 10 secs backward and play work as expected. However, the seek bar doesn't work. You can drag it, but it always returns to the "current time" instead of the "new time".

**Comment by Glitch9Inc** [comment] 2024-06-29 09:49
> Stop, 10 secs forward, 10 secs backward and play work as expected. However, the seek bar doesn't work. You can drag it, but it always returns to the "current time" instead of the "new time".

Just tested Android side and was not able to reproduce this issue. It probably got fixed while I was working on something else. Needs to confirm with [Manurocker95](https://github.com/Manurocker95)

**Comment by Glitch9Inc** [comment] 2024-07-01 00:41
> Stop, 10 secs forward, 10 secs backward and play work as expected. However, the seek bar doesn't work. You can drag it, but it always returns to the "current time" instead of the "new time".

Please close this if the recent solution works!

**Closed as completed** 2024-07-01 23:40 UTC
Labels: bug, fixed but needs testing

**Comment by Manurocker95** [comment] 2024-07-02 05:02
> > Stop, 10 secs forward, 10 secs backward and play work as expected. However, the seek bar doesn't work. You can drag it, but it always returns to the "current time" instead of the "new time".
> 
> 
> 
> Just tested Android side and was not able to reproduce this issue. It probably got fixed while I was working on something else. Needs to confirm with [Manurocker95](https://github.com/Manurocker95)
> 
> 

In the latest update the background controls' seek bar is not appearing so I can't check if it actually works. I will update if find an issue again...
